
version: '3.4'

services:
  tdm.web:
    image: ${DOCKER_REGISTRY-}tdmweb
    build:
      context: .
      dockerfile: TdM.Web/Dockerfile
    container_name: TavernaDosMundos.Web
    depends_on:
      - TavernaDb
      - TavernaAuthDb
    environment:
      ConnectionStrings__TavernaConnection: "Server=TavernaDb;Database=TavernaDb;User Id=sa;Password=PastelDosMundos@123;TrustServerCertificate=True"
      ConnectionStrings__TavernaAuthDbConnectionString: "Server=TavernaAuthDb;Database=TavernaAuthDb;User Id=sa;Password=PastelDosMundos@123;TrustServerCertificate=True"    
    ports:
      - "8000:80"
  TavernaDb:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: TavernaDb
    environment:
      SA_PASSWORD: "PastelDosMundos@123"
      ACCEPT_EULA: "Y"
      MSSQL_DATABASE: "TavernaDb"
    ports:
      - "1433:1433"
    volumes:
      - ./TavernaDbdata:/var/opt/mssql/data
  TavernaAuthDb:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: AuthDb
    environment:
      SA_PASSWORD: "PastelDosMundos@123"
      ACCEPT_EULA: "Y"
      MSSQL_DATABASE: "TavernaAuthDb"
    ports:
      - "1435:1433"
    volumes:
      - ./TavernaAuthDbdata:/var/opt/mssql/data
volumes:
  TavernaDbdata:
  TavernaAuthDbdata:
