version: '3.8'

services:
  tdm.web:
    image: ${DOCKER_REGISTRY-}tdmweb
    build:
      context: .
      dockerfile: TdM.Web/Dockerfile
    container_name: TavernaDosMundos.Web
    depends_on:
      - taverna-db
    environment:
      ConnectionStrings__TavernaConnection: "Server=taverna-db;Database=Content;User Id=sa;Password=PastelDosMundos@123;TrustServerCertificate=True"
      ConnectionStrings__TavernaAuthDbConnectionString: "Server=taverna-db;Database=Authentication;User Id=sa;Password=PastelDosMundos@123;TrustServerCertificate=True"   
    ports:
      - "80:80"
      - "443:443"
  taverna-db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: taverna-db
    environment:
      SA_PASSWORD: "PastelDosMundos@123"
      ACCEPT_EULA: "Y"
      MSSQL_DATABASE: "Content"
      MSSQL_ENCRYPT: "false"
    ports:
      - "1433:1433"
    volumes:
      - ./db-data:/var/opt/mssql/data

volumes:
  db-data:
